from tkinter import *
root = Tk()
def callback():
    print('你好呀！')
menbar = Menu(root)
filemenu = Menu(menbar,tearoff=False)
filemenu.add_command(label='打开',command=callback)
filemenu.add_command(label='保存',command=callback)
filemenu.add_separator()
filemenu.add_command(label='退出',command=root.quit)
menbar.add_cascade(label='文件',menu=filemenu)
editmenu = Menu(menbar,tearoff=False)
editmenu.add_command(label='剪切',command=callback)
editmenu.add_command(label='拷贝',command=callback)
editmenu.add_command(label='粘贴',command=callback)
menbar.add_cascade(label='编辑',menu=editmenu)
root.config(menu=menbar)
mainloop()
