from tkinter import *
m1= PanedWindow()
m1.pack(fill='both',expand=1)
left = Label(m1,text='left pane')
m1.add(left)
m2 = PanedWindow(orient='vertical')
m1.add(m2)
top = Label(m2,text='top pane')
m2.add(top)
bottom = Label(m2,text='bottom pane')
m2.add(bottom)
mainloop()
